=begin
#Venice.ai API

#The Venice.ai API.

The version of the OpenAPI document: 20250709.013306

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'

# Unit tests for VeniceClient::AudioApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AudioApi' do
  before do
    # run before each test
    @api_instance = VeniceClient::AudioApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AudioApi' do
    it 'should create an instance of AudioApi' do
      expect(@api_instance).to be_instance_of(VeniceClient::AudioApi)
    end
  end

  # unit tests for create_speech
  # /api/v1/audio/speech
  # Converts text to speech using various voice models and formats.
  # @param [Hash] opts the optional parameters
  # @option opts [CreateSpeechRequestSchema] :create_speech_request_schema 
  # @return [File]
  describe 'create_speech test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
