=begin
#Venice.ai API

#The Venice.ai API.

OpenAPI spec version: 20250521.233203

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.68
=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::BillingApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'BillingApi' do
  before do
    # run before each test
    @instance = SwaggerClient::BillingApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BillingApi' do
    it 'should create an instance of BillingApi' do
      expect(@instance).to be_instance_of(SwaggerClient::BillingApi)
    end
  end

  # unit tests for get_billing_usage
  # /api/v1/billing/usage
  # Get paginated billing usage data for the authenticated user. NOTE: This is a beta endpoint and may be subject to change.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :accept Accept header to specify the response format
  # @option opts [String] :currency 
  # @option opts [DateTime] :end_date 
  # @option opts [Integer] :limit 
  # @option opts [Integer] :page 
  # @option opts [String] :sort_order 
  # @option opts [DateTime] :start_date 
  # @return [InlineResponse20015]
  describe 'get_billing_usage test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
