=begin
#Venice.ai API

#The Venice.ai API.

OpenAPI spec version: 20250521.233203

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.68
=end

require "spec_helper"
require "json"

# Unit tests for VeniceClient::ChatApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe "ChatApi" do
  before do
    # run before each test
    @instance = VeniceClient::ChatApi.new
  end

  after do
    # run after each test
  end

  describe "test an instance of ChatApi" do
    it "should create an instance of ChatApi" do
      expect(@instance).to be_instance_of(VeniceClient::ChatApi)
    end
  end

  # unit tests for create_chat_completion
  # /api/v1/chat/completions
  # Run text inference based on the supplied parameters.
  # @param [Hash] opts the optional parameters
  # @option opts [ChatCompletionRequest] :body
  # @option opts [String] :accept_encoding Supported compression encodings (gzip, br). Only applied when stream is false.
  # @return [InlineResponse200]
  describe "create_chat_completion test" do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end
end
