=begin
#Venice.ai API

#The Venice.ai API.

The version of the OpenAPI document: 20250709.013306

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'

# Unit tests for VeniceClient::ChatApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ChatApi' do
  before do
    # run before each test
    @api_instance = VeniceClient::ChatApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ChatApi' do
    it 'should create an instance of ChatApi' do
      expect(@api_instance).to be_instance_of(VeniceClient::ChatApi)
    end
  end

  # unit tests for create_chat_completion
  # /api/v1/chat/completions
  # Run text inference based on the supplied parameters. Long running requests should use the streaming API by setting stream&#x3D;true in your request.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :accept_encoding Supported compression encodings (gzip, br). Only applied when stream is false.
  # @option opts [ChatCompletionRequest] :chat_completion_request 
  # @return [CreateChatCompletion200Response]
  describe 'create_chat_completion test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
