=begin
#Venice.ai API

#The Venice.ai API.

OpenAPI spec version: 20250521.233203

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.68
=end

require "spec_helper"
require "json"

# Unit tests for VeniceClient::EmbeddingsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe "EmbeddingsApi" do
  before do
    # run before each test
    @instance = VeniceClient::EmbeddingsApi.new
  end

  after do
    # run after each test
  end

  describe "test an instance of EmbeddingsApi" do
    it "should create an instance of EmbeddingsApi" do
      expect(@instance).to be_instance_of(VeniceClient::EmbeddingsApi)
    end
  end

  # unit tests for create_embedding
  # /api/v1/embeddings
  # Create embeddings for the supplied input. This is a beta model accessible to Venice beta testers.
  # @param body
  # @param [Hash] opts the optional parameters
  # @option opts [String] :accept_encoding Supported compression encodings (gzip, br)
  # @return [InlineResponse20014]
  describe "create_embedding test" do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end
end
