=begin
#Venice.ai API

#The Venice.ai API.

The version of the OpenAPI document: 20250709.013306

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'

# Unit tests for VeniceClient::PreviewApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PreviewApi' do
  before do
    # run before each test
    @api_instance = VeniceClient::PreviewApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PreviewApi' do
    it 'should create an instance of PreviewApi' do
      expect(@api_instance).to be_instance_of(VeniceClient::PreviewApi)
    end
  end

  # unit tests for list_characters
  # /api/v1/characters
  # This is a preview API and may change. Returns a list of characters supported in the API.
  # @param [Hash] opts the optional parameters
  # @return [ListCharacters200Response]
  describe 'list_characters test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
