=begin
#Venice.ai API

#The Venice.ai API.

OpenAPI spec version: 20250521.233203

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.68
=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::PreviewApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PreviewApi' do
  before do
    # run before each test
    @instance = SwaggerClient::PreviewApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PreviewApi' do
    it 'should create an instance of PreviewApi' do
      expect(@instance).to be_instance_of(SwaggerClient::PreviewApi)
    end
  end

  # unit tests for list_characters
  # /api/v1/characters
  # This is a preview API and may change. Returns a list of characters supported in the API.
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse20013]
  describe 'list_characters test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
