=begin
#Venice.ai API

#The Venice.ai API.

OpenAPI spec version: 20250521.233203

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.68
=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::SpeechApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SpeechApi' do
  before do
    # run before each test
    @instance = SwaggerClient::SpeechApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SpeechApi' do
    it 'should create an instance of SpeechApi' do
      expect(@instance).to be_instance_of(SwaggerClient::SpeechApi)
    end
  end

  # unit tests for create_speech
  # /api/v1/audio/speech
  # Converts text to speech using various voice models and formats.
  # @param [Hash] opts the optional parameters
  # @option opts [CreateSpeechRequestSchema] :body 
  # @return [String]
  describe 'create_speech test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
