=begin
#Venice.ai API

#The Venice.ai API.

The version of the OpenAPI document: 20251209.153516

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'

# Unit tests for VeniceClient::VideoApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'VideoApi' do
  before do
    # run before each test
    @api_instance = VeniceClient::VideoApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VideoApi' do
    it 'should create an instance of VideoApi' do
      expect(@api_instance).to be_instance_of(VeniceClient::VideoApi)
    end
  end

  # unit tests for complete_video
  # /api/v1/video/complete
  # Delete a video generation request from storage after it has been successfully downloaded. Videos can be automatically deleted after retrieval by setting the &#x60;delete_media_on_completion&#x60; flag to true when calling the retrieve API.
  # @param [Hash] opts the optional parameters
  # @option opts [CompleteVideoRequest] :complete_video_request 
  # @return [CompleteVideo200Response]
  describe 'complete_video test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for queue_video
  # /api/v1/video/queue
  # Queue a new video generation request.
  # @param [Hash] opts the optional parameters
  # @option opts [QueueVideoRequest] :queue_video_request 
  # @return [QueueVideo200Response]
  describe 'queue_video test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for quote_video
  # /api/v1/video/quote
  # Quote a video generation request. Utilizes the same parameters as the queue API and will return the price in USD for the request.
  # @param [Hash] opts the optional parameters
  # @option opts [QueueVideoRequest] :queue_video_request 
  # @return [QuoteVideo200Response]
  describe 'quote_video test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for retrieve_video
  # /api/v1/video/retrieve
  # Retrieve a video generation result. Returns the video file if completed, or a status if the request is still processing.
  # @param [Hash] opts the optional parameters
  # @option opts [RetrieveVideoRequest] :retrieve_video_request 
  # @return [RetrieveVideo200Response]
  describe 'retrieve_video test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
