=begin
#Venice.ai API

#The Venice.ai API.

OpenAPI spec version: 20250521.233203

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.68
=end

require 'date'

module VeniceClient
  class ChatCompletionRequest
    # Number between -2.0 and 2.0. Positive values penalize new tokens based on their existing frequency in the text so far, decreasing the model's likelihood to repeat the same line verbatim.
    attr_accessor :frequency_penalty

    # Whether to include log probabilities in the response. This is not supported by all models.
    attr_accessor :logprobs

    # An upper bound for the number of tokens that can be generated for a completion, including visible output tokens and reasoning tokens.
    attr_accessor :max_completion_tokens

    # Maximum temperature value for dynamic temperature scaling.
    attr_accessor :max_temp

    # The maximum number of tokens that can be generated in the chat completion. This value can be used to control costs for text generated via API. This value is now deprecated in favor of max_completion_tokens.
    attr_accessor :max_tokens

    # A list of messages comprising the conversation so far. Depending on the model you use, different message types (modalities) are supported, like text and images. For compatibility purposes, the schema supports submitting multiple image_url messages, however, only the last image_url message will be passed to and processed by the model.
    attr_accessor :messages

    # Sets a minimum probability threshold for token selection. Tokens with probabilities below this value are filtered out.
    attr_accessor :min_p

    # Minimum temperature value for dynamic temperature scaling.
    attr_accessor :min_temp

    # The ID of the model you wish to prompt. May also be a model trait, or a compatibility mapping. See the models endpoint for a list of models available to you.  You can use feature suffixes to enable features from the venice_parameters object. Please see \"Model Feature Suffix\" documentation for more details.
    attr_accessor :model

    # How many chat completion choices to generate for each input message. Note that you will be charged based on the number of generated tokens across all of the choices. Keep n as 1 to minimize costs.
    attr_accessor :n

    # Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far, increasing the model's likelihood to talk about new topics.
    attr_accessor :presence_penalty

    # The parameter for repetition penalty. 1.0 means no penalty. Values > 1.0 discourage repetition.
    attr_accessor :repetition_penalty

    # The random seed used to generate the response. This is useful for reproducibility.
    attr_accessor :seed

    # Up to 4 sequences where the API will stop generating further tokens. Defaults to null.
    attr_accessor :stop

    # Array of token IDs where the API will stop generating further tokens.
    attr_accessor :stop_token_ids

    # Whether to stream back partial progress. Defaults to false.
    attr_accessor :stream

    attr_accessor :stream_options

    # What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic. We generally recommend altering this or top_p but not both.
    attr_accessor :temperature

    # The number of highest probability vocabulary tokens to keep for top-k-filtering.
    attr_accessor :top_k

    # An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered.
    attr_accessor :top_p

    # This field is discarded on the request but is supported in the Venice API for compatibility with OpenAPI clients.
    attr_accessor :user

    attr_accessor :venice_parameters

    # Whether to enable parallel function calling during tool use.
    attr_accessor :parallel_tool_calls

    # Format in which the response should be returned.
    attr_accessor :response_format

    attr_accessor :tool_choice

    # A list of tools the model may call. Currently, only functions are supported as a tool. Use this to provide a list of functions the model may generate JSON inputs for.
    attr_accessor :tools

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'frequency_penalty' => :'frequency_penalty',
        :'logprobs' => :'logprobs',
        :'max_completion_tokens' => :'max_completion_tokens',
        :'max_temp' => :'max_temp',
        :'max_tokens' => :'max_tokens',
        :'messages' => :'messages',
        :'min_p' => :'min_p',
        :'min_temp' => :'min_temp',
        :'model' => :'model',
        :'n' => :'n',
        :'presence_penalty' => :'presence_penalty',
        :'repetition_penalty' => :'repetition_penalty',
        :'seed' => :'seed',
        :'stop' => :'stop',
        :'stop_token_ids' => :'stop_token_ids',
        :'stream' => :'stream',
        :'stream_options' => :'stream_options',
        :'temperature' => :'temperature',
        :'top_k' => :'top_k',
        :'top_p' => :'top_p',
        :'user' => :'user',
        :'venice_parameters' => :'venice_parameters',
        :'parallel_tool_calls' => :'parallel_tool_calls',
        :'response_format' => :'response_format',
        :'tool_choice' => :'tool_choice',
        :'tools' => :'tools'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'frequency_penalty' => :'Object',
        :'logprobs' => :'Object',
        :'max_completion_tokens' => :'Object',
        :'max_temp' => :'Object',
        :'max_tokens' => :'Object',
        :'messages' => :'Object',
        :'min_p' => :'Object',
        :'min_temp' => :'Object',
        :'model' => :'Object',
        :'n' => :'Object',
        :'presence_penalty' => :'Object',
        :'repetition_penalty' => :'Object',
        :'seed' => :'Object',
        :'stop' => :'Object',
        :'stop_token_ids' => :'Object',
        :'stream' => :'Object',
        :'stream_options' => :'Object',
        :'temperature' => :'Object',
        :'top_k' => :'Object',
        :'top_p' => :'Object',
        :'user' => :'Object',
        :'venice_parameters' => :'Object',
        :'parallel_tool_calls' => :'Object',
        :'response_format' => :'Object',
        :'tool_choice' => :'Object',
        :'tools' => :'Object'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'tools'
      ])
    end
  
    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `VeniceClient::ChatCompletionRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `VeniceClient::ChatCompletionRequest`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'frequency_penalty')
        self.frequency_penalty = attributes[:'frequency_penalty']
      else
        self.frequency_penalty = 0
      end

      if attributes.key?(:'logprobs')
        self.logprobs = attributes[:'logprobs']
      end

      if attributes.key?(:'max_completion_tokens')
        self.max_completion_tokens = attributes[:'max_completion_tokens']
      end

      if attributes.key?(:'max_temp')
        self.max_temp = attributes[:'max_temp']
      end

      if attributes.key?(:'max_tokens')
        self.max_tokens = attributes[:'max_tokens']
      end

      if attributes.key?(:'messages')
        if (value = attributes[:'messages']).is_a?(Array)
          self.messages = value
        end
      end

      if attributes.key?(:'min_p')
        self.min_p = attributes[:'min_p']
      end

      if attributes.key?(:'min_temp')
        self.min_temp = attributes[:'min_temp']
      end

      if attributes.key?(:'model')
        self.model = attributes[:'model']
      end

      if attributes.key?(:'n')
        self.n = attributes[:'n']
      else
        self.n = 1
      end

      if attributes.key?(:'presence_penalty')
        self.presence_penalty = attributes[:'presence_penalty']
      else
        self.presence_penalty = 0
      end

      if attributes.key?(:'repetition_penalty')
        self.repetition_penalty = attributes[:'repetition_penalty']
      end

      if attributes.key?(:'seed')
        self.seed = attributes[:'seed']
      end

      if attributes.key?(:'stop')
        self.stop = attributes[:'stop']
      end

      if attributes.key?(:'stop_token_ids')
        if (value = attributes[:'stop_token_ids']).is_a?(Array)
          self.stop_token_ids = value
        end
      end

      if attributes.key?(:'stream')
        self.stream = attributes[:'stream']
      end

      if attributes.key?(:'stream_options')
        self.stream_options = attributes[:'stream_options']
      end

      if attributes.key?(:'temperature')
        self.temperature = attributes[:'temperature']
      else
        self.temperature = 0.3
      end

      if attributes.key?(:'top_k')
        self.top_k = attributes[:'top_k']
      end

      if attributes.key?(:'top_p')
        self.top_p = attributes[:'top_p']
      else
        self.top_p = 1
      end

      if attributes.key?(:'user')
        self.user = attributes[:'user']
      end

      if attributes.key?(:'venice_parameters')
        self.venice_parameters = attributes[:'venice_parameters']
      end

      if attributes.key?(:'parallel_tool_calls')
        self.parallel_tool_calls = attributes[:'parallel_tool_calls']
      else
        self.parallel_tool_calls = true
      end

      if attributes.key?(:'response_format')
        self.response_format = attributes[:'response_format']
      end

      if attributes.key?(:'tool_choice')
        self.tool_choice = attributes[:'tool_choice']
      end

      if attributes.key?(:'tools')
        if (value = attributes[:'tools']).is_a?(Array)
          self.tools = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @messages.nil?
        invalid_properties.push('invalid value for "messages", messages cannot be nil.')
      end

      if @model.nil?
        invalid_properties.push('invalid value for "model", model cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @messages.nil?
      return false if @model.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          frequency_penalty == o.frequency_penalty &&
          logprobs == o.logprobs &&
          max_completion_tokens == o.max_completion_tokens &&
          max_temp == o.max_temp &&
          max_tokens == o.max_tokens &&
          messages == o.messages &&
          min_p == o.min_p &&
          min_temp == o.min_temp &&
          model == o.model &&
          n == o.n &&
          presence_penalty == o.presence_penalty &&
          repetition_penalty == o.repetition_penalty &&
          seed == o.seed &&
          stop == o.stop &&
          stop_token_ids == o.stop_token_ids &&
          stream == o.stream &&
          stream_options == o.stream_options &&
          temperature == o.temperature &&
          top_k == o.top_k &&
          top_p == o.top_p &&
          user == o.user &&
          venice_parameters == o.venice_parameters &&
          parallel_tool_calls == o.parallel_tool_calls &&
          response_format == o.response_format &&
          tool_choice == o.tool_choice &&
          tools == o.tools
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [frequency_penalty, logprobs, max_completion_tokens, max_temp, max_tokens, messages, min_p, min_temp, model, n, presence_penalty, repetition_penalty, seed, stop, stop_token_ids, stream, stream_options, temperature, top_k, top_p, user, venice_parameters, parallel_tool_calls, response_format, tool_choice, tools].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        elsif attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        VeniceClient.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end  end
end
