=begin
#Venice.ai API

#The Venice.ai API.

The version of the OpenAPI document: 20251218.042551

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'date'
require 'time'

module VeniceClient
  class QueueVideoRequest
    # The model to use for image generation.
    attr_accessor :model

    # The prompt to use for video generation. The maximum length is 2500 characters.
    attr_accessor :prompt

    # The negative prompt to use for video generation. The maximum length is 2500 characters.
    attr_accessor :negative_prompt

    # The duration of the video to generate.
    attr_accessor :duration

    # The aspect ratio of the video to generate.
    attr_accessor :aspect_ratio

    # The resolution of the video to generate.
    attr_accessor :resolution

    # For models which support audio generation and configuration, indicates if audio should be generated. Defaults to true.
    attr_accessor :audio

    # For image to video models, the reference image to use for video generation. Must be either a URL (starting with \"http://\" or \"https://\") or a data URL (starting with \"data:\").
    attr_accessor :image_url

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'model' => :'model',
        :'prompt' => :'prompt',
        :'negative_prompt' => :'negative_prompt',
        :'duration' => :'duration',
        :'aspect_ratio' => :'aspect_ratio',
        :'resolution' => :'resolution',
        :'audio' => :'audio',
        :'image_url' => :'image_url'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'model' => :'String',
        :'prompt' => :'String',
        :'negative_prompt' => :'String',
        :'duration' => :'String',
        :'aspect_ratio' => :'Object',
        :'resolution' => :'String',
        :'audio' => :'Object',
        :'image_url' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'aspect_ratio',
        :'audio',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `VeniceClient::QueueVideoRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `VeniceClient::QueueVideoRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'model')
        self.model = attributes[:'model']
      else
        self.model = nil
      end

      if attributes.key?(:'prompt')
        self.prompt = attributes[:'prompt']
      else
        self.prompt = nil
      end

      if attributes.key?(:'negative_prompt')
        self.negative_prompt = attributes[:'negative_prompt']
      else
        self.negative_prompt = 'low resolution, error, worst quality, low quality, defects'
      end

      if attributes.key?(:'duration')
        self.duration = attributes[:'duration']
      else
        self.duration = nil
      end

      if attributes.key?(:'aspect_ratio')
        self.aspect_ratio = attributes[:'aspect_ratio']
      end

      if attributes.key?(:'resolution')
        self.resolution = attributes[:'resolution']
      else
        self.resolution = '720p'
      end

      if attributes.key?(:'audio')
        self.audio = attributes[:'audio']
      end

      if attributes.key?(:'image_url')
        self.image_url = attributes[:'image_url']
      else
        self.image_url = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @model.nil?
        invalid_properties.push('invalid value for "model", model cannot be nil.')
      end

      if @prompt.nil?
        invalid_properties.push('invalid value for "prompt", prompt cannot be nil.')
      end

      if @prompt.to_s.length > 2500
        invalid_properties.push('invalid value for "prompt", the character length must be smaller than or equal to 2500.')
      end

      if @prompt.to_s.length < 1
        invalid_properties.push('invalid value for "prompt", the character length must be greater than or equal to 1.')
      end

      if !@negative_prompt.nil? && @negative_prompt.to_s.length > 2500
        invalid_properties.push('invalid value for "negative_prompt", the character length must be smaller than or equal to 2500.')
      end

      if @duration.nil?
        invalid_properties.push('invalid value for "duration", duration cannot be nil.')
      end

      if @image_url.nil?
        invalid_properties.push('invalid value for "image_url", image_url cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @model.nil?
      return false if @prompt.nil?
      return false if @prompt.to_s.length > 2500
      return false if @prompt.to_s.length < 1
      return false if !@negative_prompt.nil? && @negative_prompt.to_s.length > 2500
      return false if @duration.nil?
      duration_validator = EnumAttributeValidator.new('String', ["5s", "10s"])
      return false unless duration_validator.valid?(@duration)
      resolution_validator = EnumAttributeValidator.new('String', ["1080p", "720p", "480p"])
      return false unless resolution_validator.valid?(@resolution)
      return false if @image_url.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] model Value to be assigned
    def model=(model)
      if model.nil?
        fail ArgumentError, 'model cannot be nil'
      end

      @model = model
    end

    # Custom attribute writer method with validation
    # @param [Object] prompt Value to be assigned
    def prompt=(prompt)
      if prompt.nil?
        fail ArgumentError, 'prompt cannot be nil'
      end

      if prompt.to_s.length > 2500
        fail ArgumentError, 'invalid value for "prompt", the character length must be smaller than or equal to 2500.'
      end

      if prompt.to_s.length < 1
        fail ArgumentError, 'invalid value for "prompt", the character length must be greater than or equal to 1.'
      end

      @prompt = prompt
    end

    # Custom attribute writer method with validation
    # @param [Object] negative_prompt Value to be assigned
    def negative_prompt=(negative_prompt)
      if negative_prompt.nil?
        fail ArgumentError, 'negative_prompt cannot be nil'
      end

      if negative_prompt.to_s.length > 2500
        fail ArgumentError, 'invalid value for "negative_prompt", the character length must be smaller than or equal to 2500.'
      end

      @negative_prompt = negative_prompt
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] duration Object to be assigned
    def duration=(duration)
      validator = EnumAttributeValidator.new('String', ["5s", "10s"])
      unless validator.valid?(duration)
        fail ArgumentError, "invalid value for \"duration\", must be one of #{validator.allowable_values}."
      end
      @duration = duration
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] resolution Object to be assigned
    def resolution=(resolution)
      validator = EnumAttributeValidator.new('String', ["1080p", "720p", "480p"])
      unless validator.valid?(resolution)
        fail ArgumentError, "invalid value for \"resolution\", must be one of #{validator.allowable_values}."
      end
      @resolution = resolution
    end

    # Custom attribute writer method with validation
    # @param [Object] image_url Value to be assigned
    def image_url=(image_url)
      if image_url.nil?
        fail ArgumentError, 'image_url cannot be nil'
      end

      @image_url = image_url
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          model == o.model &&
          prompt == o.prompt &&
          negative_prompt == o.negative_prompt &&
          duration == o.duration &&
          aspect_ratio == o.aspect_ratio &&
          resolution == o.resolution &&
          audio == o.audio &&
          image_url == o.image_url
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [model, prompt, negative_prompt, duration, aspect_ratio, resolution, audio, image_url].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = VeniceClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
