=begin
#Venice.ai API

#The Venice.ai API.

OpenAPI spec version: 20250521.233203

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.68
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::AnyOfinlineResponse200PromptLogprobs
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AnyOfinlineResponse200PromptLogprobs' do
  before do
    # run before each test
    @instance = SwaggerClient::AnyOfinlineResponse200PromptLogprobs.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AnyOfinlineResponse200PromptLogprobs' do
    it 'should create an instance of AnyOfinlineResponse200PromptLogprobs' do
      expect(@instance).to be_instance_of(SwaggerClient::AnyOfinlineResponse200PromptLogprobs)
    end
  end
end
