=begin
#Venice.ai API

#The Venice.ai API.

OpenAPI spec version: 20250521.233203

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.68
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for VeniceClient::ApiKeysGenerateWeb3KeyBody
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ApiKeysGenerateWeb3KeyBody' do
  before do
    # run before each test
    @instance = VeniceClient::ApiKeysGenerateWeb3KeyBody.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ApiKeysGenerateWeb3KeyBody' do
    it 'should create an instance of ApiKeysGenerateWeb3KeyBody' do
      expect(@instance).to be_instance_of(VeniceClient::ApiKeysGenerateWeb3KeyBody)
    end
  end
  describe 'test attribute "api_key_type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["INFERENCE", "ADMIN"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.api_key_type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "consumption_limit"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "description"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "expires_at"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "address"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "signature"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "token"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
