=begin
#Venice.ai API

#The Venice.ai API.

The version of the OpenAPI document: 20250709.013306

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for VeniceClient::CreateChatCompletion200ResponseChoicesInnerMessage
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe VeniceClient::CreateChatCompletion200ResponseChoicesInnerMessage do
  it 'builds an AssistantMessage even when payload includes unknown keys' do
    payload = {
      role: 'assistant',
      content: 'hello',
      refusal: nil,
      annotations: nil,
      audio: nil,
      function_call: nil,
      tool_calls: [],
      reasoning: 'extra server field not in schema'
    }

    message = described_class.build(payload)
    expect(message).to be_a(VeniceClient::AssistantMessage)
    expect(message.role).to eq('assistant')
    expect(message.content).to eq('hello')
  end
end
