=begin
#Venice.ai API

#The Venice.ai API.

The version of the OpenAPI document: 20250709.013306

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for VeniceClient::CreateChatCompletion200ResponseVeniceParametersWebSearchCitationsInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe VeniceClient::CreateChatCompletion200ResponseVeniceParametersWebSearchCitationsInner do
  let(:instance) { VeniceClient::CreateChatCompletion200ResponseVeniceParametersWebSearchCitationsInner.new }

  describe 'test an instance of CreateChatCompletion200ResponseVeniceParametersWebSearchCitationsInner' do
    it 'should create an instance of CreateChatCompletion200ResponseVeniceParametersWebSearchCitationsInner' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(VeniceClient::CreateChatCompletion200ResponseVeniceParametersWebSearchCitationsInner)
    end
  end

  describe 'test attribute "content"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "date"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "title"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "url"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
