=begin
#Venice.ai API

#The Venice.ai API.

The version of the OpenAPI document: 20250709.013306

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for VeniceClient::GetApiKeys200ResponseDataInnerUsage
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe VeniceClient::GetApiKeys200ResponseDataInnerUsage do
  let(:instance) { VeniceClient::GetApiKeys200ResponseDataInnerUsage.new }

  describe 'test an instance of GetApiKeys200ResponseDataInnerUsage' do
    it 'should create an instance of GetApiKeys200ResponseDataInnerUsage' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(VeniceClient::GetApiKeys200ResponseDataInnerUsage)
    end
  end

  describe 'test attribute "trailing_seven_days"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
