=begin
#Venice.ai API

#The Venice.ai API.

The version of the OpenAPI document: 20250709.013306

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for VeniceClient::GetApiKeyRateLimitLogs200ResponseDataInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe VeniceClient::GetApiKeyRateLimitLogs200ResponseDataInner do
  let(:instance) { VeniceClient::GetApiKeyRateLimitLogs200ResponseDataInner.new }

  describe 'test an instance of GetApiKeyRateLimitLogs200ResponseDataInner' do
    it 'should create an instance of GetApiKeyRateLimitLogs200ResponseDataInner' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(VeniceClient::GetApiKeyRateLimitLogs200ResponseDataInner)
    end
  end

  describe 'test attribute "api_key_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "model_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "rate_limit_tier"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "rate_limit_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "timestamp"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
