=begin
#Venice.ai API

#The Venice.ai API.

The version of the OpenAPI document: 20250709.013306

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for VeniceClient::GetBillingUsage200ResponseDataInnerInferenceDetails
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe VeniceClient::GetBillingUsage200ResponseDataInnerInferenceDetails do
  let(:instance) { VeniceClient::GetBillingUsage200ResponseDataInnerInferenceDetails.new }

  describe 'test an instance of GetBillingUsage200ResponseDataInnerInferenceDetails' do
    it 'should create an instance of GetBillingUsage200ResponseDataInnerInferenceDetails' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(VeniceClient::GetBillingUsage200ResponseDataInnerInferenceDetails)
    end
  end

  describe 'test attribute "completion_tokens"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "inference_execution_time"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "prompt_tokens"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "request_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
