=begin
#Venice.ai API

#The Venice.ai API.

The version of the OpenAPI document: 20250709.013306

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for VeniceClient::GetApiKeyRateLimits200ResponseDataRateLimitsInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe VeniceClient::GetApiKeyRateLimits200ResponseDataRateLimitsInner do
  let(:instance) { VeniceClient::GetApiKeyRateLimits200ResponseDataRateLimitsInner.new }

  describe 'test an instance of GetApiKeyRateLimits200ResponseDataRateLimitsInner' do
    it 'should create an instance of GetApiKeyRateLimits200ResponseDataRateLimitsInner' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(VeniceClient::GetApiKeyRateLimits200ResponseDataRateLimitsInner)
    end
  end

  describe 'test attribute "api_model_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "rate_limits"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
