=begin
#Venice.ai API

#The Venice.ai API.

OpenAPI spec version: 20250521.233203

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.68
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::InlineResponse20010DataBalances
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'InlineResponse20010DataBalances' do
  before do
    # run before each test
    @instance = SwaggerClient::InlineResponse20010DataBalances.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InlineResponse20010DataBalances' do
    it 'should create an instance of InlineResponse20010DataBalances' do
      expect(@instance).to be_instance_of(SwaggerClient::InlineResponse20010DataBalances)
    end
  end
  describe 'test attribute "usd"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "vcu"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
