=begin
#Venice.ai API

#The Venice.ai API.

The version of the OpenAPI document: 20251218.042551

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for VeniceClient::InputAudio
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe VeniceClient::InputAudio do
  let(:instance) { VeniceClient::InputAudio.new }

  describe 'test an instance of InputAudio' do
    it 'should create an instance of InputAudio' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(VeniceClient::InputAudio)
    end
  end

  describe 'test attribute "cache_control"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "input_audio"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["input_audio"])
      # validator.allowable_values.each do |value|
      #   expect { instance.type = value }.not_to raise_error
      # end
    end
  end

end
