=begin
#Venice.ai API

#The Venice.ai API.

The version of the OpenAPI document: 20250918.173746

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for VeniceClient::StandardError
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe VeniceClient::StandardError do
  let(:instance) { VeniceClient::StandardError.new }

  describe 'test an instance of StandardError' do
    it 'should create an instance of StandardError' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(VeniceClient::StandardError)
    end
  end

  describe 'test attribute "error"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
