=begin
#Venice.ai API

#The Venice.ai API.

The version of the OpenAPI document: 20250709.013306

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for VeniceClient::Text
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe VeniceClient::Text do
  let(:instance) { VeniceClient::Text.new }

  describe 'test an instance of Text' do
    it 'should create an instance of Text' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(VeniceClient::Text)
    end
  end

  describe 'test attribute "text"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["text"])
      # validator.allowable_values.each do |value|
      #   expect { instance.type = value }.not_to raise_error
      # end
    end
  end

end
