=begin
#Venice.ai API

#The Venice.ai API.

OpenAPI spec version: 20250521.233203

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.68
=end

# Common files
require "venice_client/api_client"
require "venice_client/api_error"
require "venice_client/version"
require "venice_client/configuration"

# Models
require "venice_client/models/any_of_chat_completion_request_messages_items"
require "venice_client/models/any_of_chat_completion_request_stop"
require "venice_client/models/any_of_chat_completion_request_tool_choice"
require "venice_client/models/any_of_create_embedding_request_schema_input"
require "venice_client/models/any_of_create_embedding_request_schema_model"
require "venice_client/models/any_of_model_response_model_spec_constraints"
require "venice_client/models/any_of_model_response_model_spec_pricing"
require "venice_client/models/any_of_upscale_image_request_enhance"
require "venice_client/models/any_of_upscale_image_request_image"
require "venice_client/models/any_ofapi_keys_body_expires_at"
require "venice_client/models/any_ofapi_keys_consumption_limit_usd"
require "venice_client/models/any_ofapi_keys_consumption_limit_vcu"
require "venice_client/models/any_ofapi_keys_generate_web3_key_body_expires_at"
require "venice_client/models/any_ofinline_response_200_2_data_items"
require "venice_client/models/any_ofinline_response_200_4_type"
require "venice_client/models/any_ofinline_response_200_5_type"
require "venice_client/models/any_ofinline_response_200_6_type"
require "venice_client/models/any_ofinline_response_200_choices_message"
require "venice_client/models/any_ofinline_response_200_prompt_logprobs"
require "venice_client/models/api_keys_body"
require "venice_client/models/api_keys_consumption_limit"
require "venice_client/models/api_keys_generate_web3_key_body"
require "venice_client/models/billing_usage_request"
require "venice_client/models/billing_usage_response"
require "venice_client/models/billing_usage_response_data"
require "venice_client/models/billing_usage_response_inference_details"
require "venice_client/models/billing_usage_response_pagination"
require "venice_client/models/chat_completion_request"
require "venice_client/models/chat_completion_request_function"
require "venice_client/models/chat_completion_request_stream_options"
require "venice_client/models/chat_completion_request_venice_parameters"
require "venice_client/models/create_embedding_request_schema"
require "venice_client/models/create_speech_request_schema"
require "venice_client/models/generate_image_request"
require "venice_client/models/inline_response_200"
require "venice_client/models/inline_response_200_1"
require "venice_client/models/inline_response_200_10"
require "venice_client/models/inline_response_200_10_data"
require "venice_client/models/inline_response_200_10_data_api_tier"
require "venice_client/models/inline_response_200_10_data_balances"
require "venice_client/models/inline_response_200_10_data_rate_limits"
require "venice_client/models/inline_response_200_10_data_rate_limits_1"
require "venice_client/models/inline_response_200_11"
require "venice_client/models/inline_response_200_11_data"
require "venice_client/models/inline_response_200_12"
require "venice_client/models/inline_response_200_12_data"
require "venice_client/models/inline_response_200_13"
require "venice_client/models/inline_response_200_13_data"
require "venice_client/models/inline_response_200_13_stats"
require "venice_client/models/inline_response_200_14"
require "venice_client/models/inline_response_200_14_data"
require "venice_client/models/inline_response_200_14_usage"
require "venice_client/models/inline_response_200_15"
require "venice_client/models/inline_response_200_1_timing"
require "venice_client/models/inline_response_200_2"
require "venice_client/models/inline_response_200_3"
require "venice_client/models/inline_response_200_4"
require "venice_client/models/inline_response_200_5"
require "venice_client/models/inline_response_200_6"
require "venice_client/models/inline_response_200_7"
require "venice_client/models/inline_response_200_7_data"
require "venice_client/models/inline_response_200_7_usage"
require "venice_client/models/inline_response_200_7_usage_trailing_seven_days"
require "venice_client/models/inline_response_200_8"
require "venice_client/models/inline_response_200_8_data"
require "venice_client/models/inline_response_200_9"
require "venice_client/models/inline_response_200_choices"
require "venice_client/models/inline_response_200_logprobs"
require "venice_client/models/inline_response_200_logprobs_top_logprobs"
require "venice_client/models/inline_response_200_usage"
require "venice_client/models/inline_response_200_venice_parameters"
require "venice_client/models/inline_response_200_venice_parameters_web_search_citations"
require "venice_client/models/inline_response_400"
require "venice_client/models/inline_response_401"
require "venice_client/models/inline_response_402"
require "venice_client/models/inline_response_403"
require "venice_client/models/inline_response_415"
require "venice_client/models/inline_response_429"
require "venice_client/models/inline_response_500"
require "venice_client/models/inline_response_500_1"
require "venice_client/models/inline_response_503"
require "venice_client/models/model_compatibility_schema"
require "venice_client/models/model_response"
require "venice_client/models/model_response_model_spec"
require "venice_client/models/model_response_model_spec_capabilities"
require "venice_client/models/model_trait_schema"
require "venice_client/models/one_of_chat_completion_request_response_format"
require "venice_client/models/simple_generate_image_request"
require "venice_client/models/tool_call"
require "venice_client/models/type"
require "venice_client/models/upscale_image_request"

# APIs
require "venice_client/api/api_keys_api"
require "venice_client/api/audio_api"
require "venice_client/api/billing_api"
require "venice_client/api/characters_api"
require "venice_client/api/chat_api"
require "venice_client/api/embeddings_api"
require "venice_client/api/image_api"
require "venice_client/api/models_api"
require "venice_client/api/preview_api"
require "venice_client/api/speech_api"

module VeniceClient
  class << self
    # Customize default settings for the SDK using block.
    #   VeniceClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
