=begin
#Venice.ai API

#The Venice.ai API.

The version of the OpenAPI document: 20251209.153516

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

# Common files
require 'venice_client/api_client'
require 'venice_client/api_error'
require 'venice_client/version'
require 'venice_client/configuration'

# Models
require 'venice_client/models/assistant_message'
require 'venice_client/models/assistant_message_content'
require 'venice_client/models/audio_model_pricing'
require 'venice_client/models/audio_model_pricing_input'
require 'venice_client/models/billing_usage_request'
require 'venice_client/models/billing_usage_response'
require 'venice_client/models/cache_control'
require 'venice_client/models/chat_completion_request'
require 'venice_client/models/chat_completion_request_messages_inner'
require 'venice_client/models/chat_completion_request_reasoning'
require 'venice_client/models/chat_completion_request_response_format'
require 'venice_client/models/chat_completion_request_stop'
require 'venice_client/models/chat_completion_request_stream_options'
require 'venice_client/models/chat_completion_request_tool_choice'
require 'venice_client/models/chat_completion_request_tool_choice_any_of'
require 'venice_client/models/chat_completion_request_tool_choice_any_of_function'
require 'venice_client/models/chat_completion_request_venice_parameters'
require 'venice_client/models/complete_video200_response'
require 'venice_client/models/complete_video_request'
require 'venice_client/models/create_api_key200_response'
require 'venice_client/models/create_api_key200_response_data'
require 'venice_client/models/create_api_key_request'
require 'venice_client/models/create_api_key_request_expires_at'
require 'venice_client/models/create_chat_completion200_response'
require 'venice_client/models/create_chat_completion200_response_choices_inner'
require 'venice_client/models/create_chat_completion200_response_choices_inner_logprobs'
require 'venice_client/models/create_chat_completion200_response_choices_inner_logprobs_top_logprobs_inner'
require 'venice_client/models/create_chat_completion200_response_choices_inner_message'
require 'venice_client/models/create_chat_completion200_response_usage'
require 'venice_client/models/create_chat_completion200_response_venice_parameters'
require 'venice_client/models/create_chat_completion200_response_venice_parameters_web_search_citations_inner'
require 'venice_client/models/create_embedding200_response'
require 'venice_client/models/create_embedding200_response_data_inner'
require 'venice_client/models/create_embedding200_response_usage'
require 'venice_client/models/create_embedding_request_schema'
require 'venice_client/models/create_embedding_request_schema_input'
require 'venice_client/models/create_embedding_request_schema_model'
require 'venice_client/models/create_speech_request_schema'
require 'venice_client/models/delete_api_key200_response'
require 'venice_client/models/detailed_error'
require 'venice_client/models/edit_image_request'
require 'venice_client/models/edit_image_request_image'
require 'venice_client/models/generate_image200_response'
require 'venice_client/models/generate_image200_response_timing'
require 'venice_client/models/generate_image_request'
require 'venice_client/models/get_api_key_by_id200_response'
require 'venice_client/models/get_api_key_by_id200_response_data'
require 'venice_client/models/get_api_key_generate_web3_key200_response'
require 'venice_client/models/get_api_key_generate_web3_key200_response_data'
require 'venice_client/models/get_api_key_rate_limit_logs200_response'
require 'venice_client/models/get_api_key_rate_limit_logs200_response_data_inner'
require 'venice_client/models/get_api_key_rate_limits200_response'
require 'venice_client/models/get_api_key_rate_limits200_response_data'
require 'venice_client/models/get_api_key_rate_limits200_response_data_api_tier'
require 'venice_client/models/get_api_key_rate_limits200_response_data_balances'
require 'venice_client/models/get_api_key_rate_limits200_response_data_rate_limits_inner'
require 'venice_client/models/get_api_key_rate_limits200_response_data_rate_limits_inner_rate_limits_inner'
require 'venice_client/models/get_api_keys200_response'
require 'venice_client/models/get_api_keys200_response_data_inner'
require 'venice_client/models/get_api_keys200_response_data_inner_consumption_limits'
require 'venice_client/models/get_api_keys200_response_data_inner_usage'
require 'venice_client/models/get_api_keys200_response_data_inner_usage_trailing_seven_days'
require 'venice_client/models/get_billing_usage200_response'
require 'venice_client/models/get_billing_usage200_response_data_inner'
require 'venice_client/models/get_billing_usage200_response_data_inner_inference_details'
require 'venice_client/models/get_billing_usage200_response_pagination'
require 'venice_client/models/get_character_by_slug200_response'
require 'venice_client/models/image_model_constraints'
require 'venice_client/models/image_model_constraints_steps'
require 'venice_client/models/image_model_pricing'
require 'venice_client/models/image_model_pricing_generation'
require 'venice_client/models/image_model_pricing_upscale'
require 'venice_client/models/image_model_pricing_upscale2x'
require 'venice_client/models/image_model_pricing_upscale4x'
require 'venice_client/models/image_styles_get200_response'
require 'venice_client/models/image_url_object'
require 'venice_client/models/image_url'
require 'venice_client/models/json_object'
require 'venice_client/models/json_schema'
require 'venice_client/models/llm_model_pricing'
require 'venice_client/models/llm_model_pricing_input'
require 'venice_client/models/llm_model_pricing_output'
require 'venice_client/models/list_characters200_response'
require 'venice_client/models/list_characters200_response_data_inner'
require 'venice_client/models/list_characters200_response_data_inner_stats'
require 'venice_client/models/list_model_compatibility_mapping200_response'
require 'venice_client/models/list_model_traits200_response'
require 'venice_client/models/list_models200_response'
require 'venice_client/models/list_models200_response_type'
require 'venice_client/models/list_models_type_parameter'
require 'venice_client/models/model_response'
require 'venice_client/models/model_response_model_spec'
require 'venice_client/models/model_response_model_spec_capabilities'
require 'venice_client/models/model_response_model_spec_constraints'
require 'venice_client/models/model_response_model_spec_pricing'
require 'venice_client/models/objects_inner'
require 'venice_client/models/post_api_key_generate_web3_key_request'
require 'venice_client/models/queue_video200_response'
require 'venice_client/models/queue_video_request'
require 'venice_client/models/quote_video200_response'
require 'venice_client/models/retrieve_video200_response'
require 'venice_client/models/retrieve_video_request'
require 'venice_client/models/simple_generate_image200_response'
require 'venice_client/models/simple_generate_image200_response_data_inner'
require 'venice_client/models/simple_generate_image200_response_data_inner_any_of'
require 'venice_client/models/simple_generate_image200_response_data_inner_any_of1'
require 'venice_client/models/simple_generate_image_request'
require 'venice_client/models/standard_error'
require 'venice_client/models/system_message'
require 'venice_client/models/system_message_content'
require 'venice_client/models/text'
require 'venice_client/models/text_model_constraints'
require 'venice_client/models/text_model_constraints_temperature'
require 'venice_client/models/text_model_constraints_top_p'
require 'venice_client/models/tool_call'
require 'venice_client/models/tool_call_function'
require 'venice_client/models/tool_message'
require 'venice_client/models/upscale_image_request'
require 'venice_client/models/upscale_image_request_enhance'
require 'venice_client/models/user_message'
require 'venice_client/models/user_message_content'
require 'venice_client/models/video_model_constraints'

# APIs
require 'venice_client/api/api_keys_api'
require 'venice_client/api/audio_api'
require 'venice_client/api/billing_api'
require 'venice_client/api/characters_api'
require 'venice_client/api/chat_api'
require 'venice_client/api/embeddings_api'
require 'venice_client/api/image_api'
require 'venice_client/api/models_api'
require 'venice_client/api/preview_api'
require 'venice_client/api/speech_api'
require 'venice_client/api/video_api'

module VeniceClient
  class << self
    # Customize default settings for the SDK using block.
    #   VeniceClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
