=begin
#Venice.ai API

#The Venice.ai API.

The version of the OpenAPI document: 20250918.173746

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'cgi'

module VeniceClient
  class EmbeddingsApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # /api/v1/embeddings
    # Create embeddings for the supplied input.
    # @param create_embedding_request_schema [CreateEmbeddingRequestSchema] 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :accept_encoding Supported compression encodings (gzip, br)
    # @return [CreateEmbedding200Response]
    def create_embedding(create_embedding_request_schema, opts = {})
      data, _status_code, _headers = create_embedding_with_http_info(create_embedding_request_schema, opts)
      data
    end

    # /api/v1/embeddings
    # Create embeddings for the supplied input.
    # @param create_embedding_request_schema [CreateEmbeddingRequestSchema] 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :accept_encoding Supported compression encodings (gzip, br)
    # @return [Array<(CreateEmbedding200Response, Integer, Hash)>] CreateEmbedding200Response data, response status code and response headers
    def create_embedding_with_http_info(create_embedding_request_schema, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: EmbeddingsApi.create_embedding ...'
      end
      # verify the required parameter 'create_embedding_request_schema' is set
      if @api_client.config.client_side_validation && create_embedding_request_schema.nil?
        fail ArgumentError, "Missing the required parameter 'create_embedding_request_schema' when calling EmbeddingsApi.create_embedding"
      end
      # resource path
      local_var_path = '/embeddings'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'Accept-Encoding'] = opts[:'accept_encoding'] if !opts[:'accept_encoding'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(create_embedding_request_schema)

      # return_type
      return_type = opts[:debug_return_type] || 'CreateEmbedding200Response'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['BearerAuth']

      new_options = opts.merge(
        :operation => :"EmbeddingsApi.create_embedding",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: EmbeddingsApi#create_embedding\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
