=begin
#Venice.ai API

#The Venice.ai API.

OpenAPI spec version: 20250521.233203

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.68
=end

module VeniceClient
  class SpeechApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # /api/v1/audio/speech
    # Converts text to speech using various voice models and formats.
    # @param [Hash] opts the optional parameters
    # @option opts [CreateSpeechRequestSchema] :body 
    # @return [String]
    def create_speech(opts = {})
      data, _status_code, _headers = create_speech_with_http_info(opts)
      data
    end

    # /api/v1/audio/speech
    # Converts text to speech using various voice models and formats.
    # @param [Hash] opts the optional parameters
    # @option opts [CreateSpeechRequestSchema] :body 
    # @return [Array<(String, Integer, Hash)>] String data, response status code and response headers
    def create_speech_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: SpeechApi.create_speech ...'
      end
      # resource path
      local_var_path = '/audio/speech'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['audio/aac', 'audio/flac', 'audio/mpeg', 'audio/opus', 'audio/pcm', 'audio/wav', 'application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:body] || @api_client.object_to_http_body(opts[:'body']) 

      return_type = opts[:return_type] || 'String' 

      auth_names = opts[:auth_names] || ['BearerAuth']
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type)

      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: SpeechApi#create_speech\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
